<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
class Job extends Model
{
    protected $fillable = ['user_id','company_id','title','slug','description','roles','type','category_id','position','address','status','last_date'];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function company(){
        return $this->belongsTo('App\Company');
    }

    public function users(){
        return $this->belongsToMany('App\User')->withTimeStamps();
    }

    public function checkApplication(){
        return \DB::table('job_user')->where('user_id',Auth::user()->id)
                              ->where('job_id',$this->id)
                              ->exists();
    }
}
