<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = ['user_id','company_id','title','slug','description','roles','type','category_id','position','address','status','last_date'];
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function company(){
        return $this->belongsTo('App\Company');
    }
}
